/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as HelpersIndexRouteImport } from './routes/helpers.index'
import { Route as HelpersHelperIdRouteImport } from './routes/helpers.$helperId'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as WorkerEarningsRouteImport } from './routes/worker.earnings'
import { Route as WorkerOnboardingRouteImport } from './routes/worker.onboarding'
import { Route as WorkerProfileRouteImport } from './routes/worker.profile'
import { Route as WorkerRequestsRouteImport } from './routes/worker.requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpersIndexRoute = HelpersIndexRouteImport.update({
  id: '/helpers/',
  path: '/helpers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpersHelperIdRoute = HelpersHelperIdRouteImport.update({
  id: '/helpers/$helperId',
  path: '/helpers/$helperId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerEarningsRoute = WorkerEarningsRouteImport.update({
  id: '/worker/earnings',
  path: '/worker/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerOnboardingRoute = WorkerOnboardingRouteImport.update({
  id: '/worker/onboarding',
  path: '/worker/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerProfileRoute = WorkerProfileRouteImport.update({
  id: '/worker/profile',
  path: '/worker/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRequestsRoute = WorkerRequestsRouteImport.update({
  id: '/worker/requests',
  path: '/worker/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/helpers/$helperId': typeof HelpersHelperIdRoute
  '/worker/earnings': typeof WorkerEarningsRoute
  '/worker/onboarding': typeof WorkerOnboardingRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/requests': typeof WorkerRequestsRoute
  '/helpers/': typeof HelpersIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/helpers/$helperId': typeof HelpersHelperIdRoute
  '/worker/earnings': typeof WorkerEarningsRoute
  '/worker/onboarding': typeof WorkerOnboardingRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/requests': typeof WorkerRequestsRoute
  '/helpers': typeof HelpersIndexRoute
  '/worker': typeof WorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/helpers/$helperId': typeof HelpersHelperIdRoute
  '/worker/earnings': typeof WorkerEarningsRoute
  '/worker/onboarding': typeof WorkerOnboardingRoute
  '/worker/profile': typeof WorkerProfileRoute
  '/worker/requests': typeof WorkerRequestsRoute
  '/helpers/': typeof HelpersIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/complaints'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/schedule'
    | '/settings'
    | '/terms'
    | '/helpers/$helperId'
    | '/worker/earnings'
    | '/worker/onboarding'
    | '/worker/profile'
    | '/worker/requests'
    | '/helpers/'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/complaints'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/schedule'
    | '/settings'
    | '/terms'
    | '/helpers/$helperId'
    | '/worker/earnings'
    | '/worker/onboarding'
    | '/worker/profile'
    | '/worker/requests'
    | '/helpers'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bookings'
    | '/complaints'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/schedule'
    | '/settings'
    | '/terms'
    | '/helpers/$helperId'
    | '/worker/earnings'
    | '/worker/onboarding'
    | '/worker/profile'
    | '/worker/requests'
    | '/helpers/'
    | '/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  HelpersHelperIdRoute: typeof HelpersHelperIdRoute
  WorkerEarningsRoute: typeof WorkerEarningsRoute
  WorkerOnboardingRoute: typeof WorkerOnboardingRoute
  WorkerProfileRoute: typeof WorkerProfileRoute
  WorkerRequestsRoute: typeof WorkerRequestsRoute
  HelpersIndexRoute: typeof HelpersIndexRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpers/': {
      id: '/helpers/'
      path: '/helpers'
      fullPath: '/helpers/'
      preLoaderRoute: typeof HelpersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpers/$helperId': {
      id: '/helpers/$helperId'
      path: '/helpers/$helperId'
      fullPath: '/helpers/$helperId'
      preLoaderRoute: typeof HelpersHelperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/earnings': {
      id: '/worker/earnings'
      path: '/worker/earnings'
      fullPath: '/worker/earnings'
      preLoaderRoute: typeof WorkerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/onboarding': {
      id: '/worker/onboarding'
      path: '/worker/onboarding'
      fullPath: '/worker/onboarding'
      preLoaderRoute: typeof WorkerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/profile': {
      id: '/worker/profile'
      path: '/worker/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/requests': {
      id: '/worker/requests'
      path: '/worker/requests'
      fullPath: '/worker/requests'
      preLoaderRoute: typeof WorkerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  HelpersHelperIdRoute: HelpersHelperIdRoute,
  WorkerEarningsRoute: WorkerEarningsRoute,
  WorkerOnboardingRoute: WorkerOnboardingRoute,
  WorkerProfileRoute: WorkerProfileRoute,
  WorkerRequestsRoute: WorkerRequestsRoute,
  HelpersIndexRoute: HelpersIndexRoute,
  WorkerIndexRoute: WorkerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
